#+ summary: Returns all Observation instances in the graph
#+ tags:
#+   - sensor-things

PREFIX sosa: <http://www.w3.org/ns/sosa/>

SELECT ?obs
FROM <http://wosis.isric.org/>
WHERE {
    ?obs a sosa:Observation .
}

